<?php

/**
 * @file
 * Test module for the entity API.
 */

include_once('fhd_person.features.inc');

/**
 * Implement hook_entity_info().
 */
function fhd_person_entity_info() {
  $return = array(
    'fhd_person' => array(
      'label' => t('Person'),
      'entity class' => 'FhdPerson',
      'controller class' => 'FhdPersonController',
      'base table' => 'fhd_person',
      'fieldable' => TRUE,
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        ),
      ),
      'entity keys' => array(
        'id' => 'pid',
        'label' => 'Person',
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'fhd_person',
    ),
  );
  return $return;
}

/**
 * Load multiple fhd_person entities based on certain conditions.
 *
 * @param $pids
 *   An array of entity IDs.
 * @param $conditions
 *   An array of conditions to match against the {entity} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of test entity objects, indexed by pid.
 */
function fhd_person_load_multiple($pids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('fhd_person', $pids, $conditions, $reset);
}

/**
 * Delete multiple test entities.
 *
 * @param $pids
 *   An array of test entity IDs.
 */
function fhd_person_delete_multiple(array $pids) {
  entity_get_controller('fhd_person')->delete($pids);
}


/**
 * Main class for test entities.
 */
class FhdPerson extends Entity {

  public function __construct(array $values = array(), $entityType = NULL) {
    parent::__construct($values, $entityType);
  }

  /**
   * Override buildContent() to add the username to the output.
   */
  public function buildContent($view_mode = 'full', $langcode = NULL) {
    $content['user'] = array(
      '#markup' => "I was here",
    );
    return entity_get_controller($this->entityType)->buildContent($this, $view_mode, $langcode, $content);
  }

  /**
   * Specifies the default label, which is picked up by label() by default.
   */
  protected function defaultLabel() {
    $type = fhd_person_get_types($this->name);
    return $type->label;
  }

  /**
   * Specifies the default uri, which is picked up by uri() by default.
   */
  protected function defaultUri() {
    return array('path' => 'person/' . $this->identifier());
  }

  /**
   * Returns the full url() for the person.
   */
  public function url() {
    $uri = $this->uri();
    return url($uri['path']);
  }

  /**
   * Returns the drupal path to this person.
   */
  public function path() {
    $uri = $this->uri();
    return url($uri['path']);
  }
}


/**
 *
 *
 * Some hook implementations used by the tests.
 *
 *
 */


/**
 * Implements hook_entity_insert().
 */
function fhd_person_entity_insert($entity, $entity_type) {

}

/**
 * Implements hook_entity_update().
 */
function fhd_person_entity_update($entity, $entity_type) {

}

/**
 * Implements hook_entity_delete().
 */
function fhd_person_entity_delete($entity, $entity_type) {

}

/**
 * Getter callback for the 'reference' property.
 */
function fhd_person_entity_getter($node) {
  if (empty($node->entity)) {
    $node->entity = array('type' => 'user', 'id' => $node->uid);
  }
  // We have to return the entity wrapped.
  return entity_metadata_wrapper($node->entity['type'], $node->entity['id']);
}

/**
 * Setter callback for the 'reference' property.
 */
function fhd_person_entity_setter($node, $property_name, $wrapper) {
  // The entity has to be passed wrapped.
  $node->entity = array('type' => $wrapper->type(), 'id' => $wrapper->getIdentifier());
}

class FhdPersonController extends EntityAPIController {

   /**
    * Overridden.
    * @see DrupalDefaultEntityController#load($ids, $conditions)
    *
    * In contrast to the parent implementation we factor out query execution, so
    * fetching can be further customized easily. Also we add any in code defined
    * objects.
    */
   public function load($ids = array(), $conditions = array()) {
     $entities = parent::load($ids, $conditions);

     // If entities return nothing and conditions have an fs id set, then we'll
     // try to fetch that person from the FHS API and save them as a new entity.
     return $entities;
   }
}

/*
 * If the person isn't already in the database, add a new entity,
 * otherwise, check if the information has changed by comparing a hash of the
 * two datasets. If the information has changed then update the database.
 */
function fhd_person_load_gedcom($file_path) {
  date_default_timezone_set(variable_get('date_default_timezone', 'America/Denver'));
  require_once 'Genealogy/Gedcom.php';

  timer_start('ged');

  // Load all Gedcom info in the Database.
  $results = db_query("SELECT * FROM {fhd_person}");
  $db_persons = array();
  foreach ($results as $row) {
    $db_persons[$row->gedcom_id] = $row;
  }

  $ged = new Genealogy_Gedcom($file_path);
  $persons = $ged->GedcomIndividualsTreeObjects;

  $count = 0;
  foreach ($persons as $person) {
    // Provide running count of the import.
    if ($count % 500 === 0 && $count !== 0) {
      echo "\n";
      echo "===== Processed " . $count . " records";
      echo "\n";
    }
    $count++;

    $db_p = $db_persons[$person->Identifier];

    $entity = array(
      'name' => fixEncoding(trim($person->Firstname) . " " . trim($person->Lastname)),
     'birth_date' => _fhd_get_date($person->Birth['Date']),
     'birth_place' => utf8_encode($person->Birth['Place']),
     'sex' => $person->Sex,
     'gedcom_id' => $person->Identifier,
    );

    // Gedcom parser duplicates birth info into death/burial if they are empty.
    // So check that death and burial aren't the same day.
    if ($person->Death['Date'] != $person->Birth['Date']) {
      $entity['death_date'] = _fhd_get_date($person->Death['Date']);
      $entity['death_place'] = utf8_encode($person->Death['Place']);
    }
    if ($person->Burial['Date'] != $person->Birth['Date']) {
      $entity['burial_date'] = _fhd_get_date($person->Burial['Date']);
      $entity['burial_place'] = utf8_encode($person->Burial['Place']);
    }

    // If this person isn't in the database, save.
    if (!array_key_exists($entity['gedcom_id'], $db_persons)) {
      echo "Creating entity for: " . $entity['name'] . "\n";
      entity_save('fhd_person', $entity);
    }
    // Else check if there's any changes.
    else {
      // Compare hashes.
      $entity_str = implode('', $entity);
      // Dates are being saved as 0 which messes up our hashing.
      if ($db_p->burial_date == "0") {
        $db_p->burial_date = "";
      }
      if ($db_p->death_date == "0") {
        $db_p->death_date = "";
      }
      if ($db_p->birth_date == "0") {
        $db_p->birth_date = "";
      }
      $person_str = $db_p->name . $db_p->birth_date . $db_p->birth_place . $db_p->sex .
        $db_p->gedcom_id . $db_p->death_date . $db_p->death_place . $db_p->burial_date .
        $db_p->burial_place;

      if (sha1($entity_str) !== sha1($person_str)) {
        // Check how far apart are dates, it seems that PHP's strtodate function
        // often returns times 20-30 minutes apart.
        if (_fhd_person_acceptable_time_diff($entity, $db_p)) {
          continue;
        }
        // Update entity.
        echo "Updating info on " . $db_p->name . "\n";
        $entity['pid'] = $db_p->pid;
        drupal_write_record('fhd_person', $entity, 'pid');
      }
    }
  }
  echo "How long this took: \n";
  print_r(timer_stop('ged'));
}

/*
 * If the time differences are within 12 hours, then return true.
 */
function _fhd_person_acceptable_time_diff($entity, $db_p) {
  if (abs($entity['burial_date'] - $db_p->burial_date) > 43200) {
    echo "big time diff in burial date \n";
    return false;
  }
  else if (abs($entity['death_date'] - $db_p->death_date) > 43200) {
    echo "big time diff in death date \n";
    return false;
  }
  else if (abs($entity['birth_date'] - $db_p->birth_date) > 43200) {
    echo "big time diff in birth date \n";
    return false;
  }
  else {
    return true;
  }
}

function fixEncoding($in_str) {
  $cur_encoding = mb_detect_encoding($in_str);
  if ($cur_encoding == "UTF-8" && mb_check_encoding($in_str, "UTF-8")) {
    return $in_str;
  }
  else{
    return utf8_encode($in_str);
  }
}

function _fhd_get_date($str) {
  $timestamp = @safestrtotime($str);
  if (!empty($timestamp)) {
    return $timestamp;
  }
  else{
    // Trim off "Abt" or other odd charecters that slip in
    $str = trim($str, ' Aabt<>Bef');
    // Sometimes there's a date range, just grab the first.
    $str = array_pop(explode('-',$str));

    $timestamp = @safestrtotime($str);
    if (!empty($timestamp)) {
      return $timestamp;
    }
    else {
      if (!empty($str)) {
        echo "the string " . $str . " is bogus\n";
      }
      return '';
    }
  }
}

function safestrtotime($strInput)
{
    $iVal = -1;
    for ($i=1000; $i<=1969; $i++)
    {
        // Check for this year string in date
        $strYear = (string)$i;
        if (!(strpos($strInput, $strYear)===false))
        {
            $replYear = $strYear;
            $yearSkew = 1970 - $i;
            $strInput = str_replace($strYear, '1970', $strInput);
        }
    }
    $iVal = strtotime($strInput);
    if ($yearSkew> 0)
    {
        $numSecs = (60 * 60 * 24 * 365 * $yearSkew);
        $iVal = $iVal - $numSecs;
        $numLeapYears = 0;  // determine number of leap years in period
        for ($j=$replYear; $j<=1969; $j++)
        {
            $thisYear = $j;
            $isLeapYear = false;
            // Is div by 4?
            if (($thisYear % 4) == 0)
            {
                $isLeapYear = true;
            }
            // Is div by 100?
            if (($thisYear % 100) == 0)
            {
                $isLeapYear = false;
            }
            // Is div by 1000?
            if (($thisYear % 1000) == 0)
            {
                $isLeapYear = true;
            }
            if ($isLeapYear == true)
            {
                $numLeapYears++;
            }
        }
        $iVal = $iVal - (60 * 60 * 24 * $numLeapYears);
    }
    return $iVal;
}


/**
 * Implementation of hook_views_pre_render().
 **/
function fhd_person_views_pre_render(&$view) {
  // Override the person page's Title with the name of the person.
  if ($view->name == "person_page_views") {
    $birth_year = "";
    if (!empty($view->result[0]->fhd_person_birth_date)) {
      $birth_year = adodb_date("Y", $view->result[0]->fhd_person_birth_date);
    }

    drupal_set_title($view->result[0]->fhd_person_name . " (" . $birth_year . ")");
  }
}
